import React from "react";
import { type ReactNode } from "react";
import Navbar from "../Navbar";
import Head from "next/head";
import SearchBox from "../SearchBox";
import type { Suggestion } from "../SearchBox/types/SearchBoxTypes";

type props = {
  children: ReactNode;
};

const Layout = ({ children, ...rest }: props) => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar {...rest} />
      {children }
    </>
  );
};
export default Layout;
